# Generated by Django 2.2 on 2020-09-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhhapp', '0002_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
